"""create_ops_dashboard_tables

Revision ID: 3f8745b1586b
Revises: f2a4c6e8b9d0
Create Date: 2026-05-18 12:58:30.401988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8745b1586b'
down_revision: Union[str, None] = 'f2a4c6e8b9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meta_account_id', sa.String(), nullable=True),
    sa.Column('google_account_id', sa.String(), nullable=True),
    sa.Column('tintim_id', sa.String(), nullable=True),
    sa.Column('active_platforms', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('campaign_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_snapshots_client_id'), 'campaign_snapshots', ['client_id'], unique=False)
    op.create_index(op.f('ix_campaign_snapshots_id'), 'campaign_snapshots', ['id'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ad_spend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('cost_per_conversion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lp_to_whatsapp_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('whatsapp_to_booking_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bookings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'week_start', 'source', name='uq_client_week_source')
    )
    op.create_index(op.f('ix_metric_snapshots_client_id'), 'metric_snapshots', ['client_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_id'), 'metric_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_snapshots_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_client_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_campaign_snapshots_id'), table_name='campaign_snapshots')
    op.drop_index(op.f('ix_campaign_snapshots_client_id'), table_name='campaign_snapshots')
    op.drop_table('campaign_snapshots')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
