"""add onboarding_id to clients

Revision ID: 7166efd789de
Revises: f5473c2e6122
Create Date: 2026-05-20 18:31:51.741436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7166efd789de'
down_revision: Union[str, None] = 'f5473c2e6122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('onboarding_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'clients', ['onboarding_id'])
    op.create_foreign_key(None, 'clients', 'onboardings', ['onboarding_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'onboarding_id')
    # ### end Alembic commands ###
