"""add date to metric snapshot

Revision ID: f5473c2e6122
Revises: 872ad2537d01
Create Date: 2026-05-20 16:43:38.028356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5473c2e6122'
down_revision: Union[str, None] = '872ad2537d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_snapshots', sa.Column('date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_metric_snapshots_date'), 'metric_snapshots', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_snapshots_date'), table_name='metric_snapshots')
    op.drop_column('metric_snapshots', 'date')
    # ### end Alembic commands ###
